version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql-chat-app
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: wouter
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: chatrooms
    networks:
      - chat-app-network
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql-chat-app
    ports:
      - 8181:80
    networks:
      - chat-app-network

  wouterfennis.chatapp:
    image: user/wouterfennis.chatapp${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      dbconnectionstring: Server=mysql-chat-app; Port=3306; Database=chatrooms; Uid=wouter; Pwd=secret; SslMode=Preferred;
    networks:
      - chat-app-network
    ports:
      - 8001:80

networks:
  chat-app-network: