version: '2'

services:
  wouterfennis.chatapp.frontend:
    image: user/wouterfennis.chatapp.frontend${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     chat-app-backend-service: http://wouterfennischatappbackend_wouterfennis.chatapp.backend_1
    networks:
      - chat-app-network
    ports:
      - 8002:80

networks:
  chat-app-network:
    external:
      name: chat-app-network